---

- name: Install nfs packages
  yum:
    name: nfs-utils
    state: present

- name: If nfs-server is present
  include_tasks: nfs-server.yml
  when: nfs_enable.server | bool or item.nfs_enable.server | bool
  loop: "{{ nfs_configurations }}"

- name: If nfs-clients is present
  include_tasks: nfs-clients.yml
  when: nfs_enable.clients | bool or item.nfs_enable.clients | bool
  loop: "{{ nfs_configurations }}"
